// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAffix: typeof import('element-plus/es')['ElAffix']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElBacktop: typeof import('element-plus/es')['ElBacktop']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
}
export {}
